/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appli;

import java.util.ArrayList;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

import appli.data.Banque;
import appli.data.Client;
import appli.data.Compte;
import appli.data.IAfficheur;
import appli.data.IDescription;
import javax.swing.table.DefaultTableModel;
import plateforme.Loader;

/**
 *
 * @author Audrey
 */
public class JFrameBanque extends javax.swing.JFrame {

	/**
	 * Creates new form JFrameBanque
	 */
	private ArrayList<IDescription> listDescriptionPluging;

	public JFrameBanque() {
		initComponents();
	}

	public void afficherCompte(Client client) {
		IAfficheur afficheur = (IAfficheur) Loader.getInstance().getPlugin(this.getListDescriptionPluging().get(1));
		ArrayList<String> donnes = null;
		ArrayList<String> entetes = afficheur.afficherEntete();
		for (Compte list : client.getComptes()) {
			donnes.addAll(afficheur.afficher((Compte) list));
		}
		this.setjTableCompte(entetes, donnes);
	}

	public void afficherClient(Banque banque) {
		IAfficheur afficheur = (IAfficheur) Loader.getInstance().getPlugin(this.getListDescriptionPluging().get(0));
                ArrayList<String> entete = afficheur.afficherEntete();
                DefaultTableModel tableModel = (DefaultTableModel) this.jTableClient.getModel();
                tableModel.setColumnIdentifiers(entete.toArray());
                ArrayList<String> unClient = new ArrayList();
                for(Client c : banque.getClients()){
                    unClient = afficheur.afficher(c);
                    tableModel.addRow(unClient.toArray());
                }
                jTableClient.setModel(tableModel);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabelClient = new javax.swing.JLabel();
		jButtonValider = new javax.swing.JButton();
		jTextFieldMontant = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTableClient = new javax.swing.JTable();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTableCompte = new javax.swing.JTable();
		jLabelCompte = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabelClient.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabelClient.setText("Liste Client :");

		jButtonValider.setText("Valider");

		jTextFieldMontant.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldMontantActionPerformed(evt);
			}
		});

		jLabel1.setText("Montant : ");

		jTableClient
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane3.setViewportView(jTableClient);

		jTableCompte
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { null, null, null, null }, { null, null, null, null },
								{ null, null, null, null }, { null, null, null, null } },
						new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane4.setViewportView(jTableCompte);

		jLabelCompte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
		jLabelCompte.setText("Liste Compte :");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(jLabelClient)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabelCompte)
								.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1).addGap(29, 29, 29)
										.addComponent(jTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE, 89,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(jButtonValider)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabelClient)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 96,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addComponent(jLabelCompte)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextFieldMontant, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1).addComponent(jButtonValider))
						.addContainerGap(28, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldMontantActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldMontantActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldMontantActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFrameBanque.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFrameBanque.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFrameBanque.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFrameBanque.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				JFrameBanque j = new JFrameBanque();
				Banque banque = new Banque();
				Loader loader = Loader.getInstance();
				j.setListDescriptionPluging(loader.getPluginsDescriptions(IAfficheur.class));
				j.afficherClient(banque);
				j.setVisible(true);
			}
		});
	}

	public JButton getjButtonValider() {
		return jButtonValider;
	}

	public void setjButtonValider(JButton jButtonValider) {
		this.jButtonValider = jButtonValider;
	}

	public JLabel getjLabel1() {
		return jLabel1;
	}

	public void setjLabel1(JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	public JLabel getjLabelClient() {
		return jLabelClient;
	}

	public void setjLabelClient(JLabel jLabelClient) {
		this.jLabelClient = jLabelClient;
	}

	public JLabel getjLabelCompte() {
		return jLabelCompte;
	}

	public void setjLabelCompte(JLabel jLabelCompte) {
		this.jLabelCompte = jLabelCompte;
	}

	public JScrollPane getjScrollPane3() {
		return jScrollPane3;
	}

	public void setjScrollPane3(JScrollPane jScrollPane3) {
		this.jScrollPane3 = jScrollPane3;
	}

	public JScrollPane getjScrollPane4() {
		return jScrollPane4;
	}

	public void setjScrollPane4(JScrollPane jScrollPane4) {
		this.jScrollPane4 = jScrollPane4;
	}

	public JTable getjTableClient() {
		return jTableClient;
	}

	public void setjTableClient(JTable jTableClient) {
		this.jTableClient = jTableClient;
	}

	public JTable getjTableCompte() {
		return jTableCompte;
	}

	public void setjTableCompte(JTable jTableCompte) {
		this.jTableCompte = jTableCompte;
	}

	public JTextField getjTextFieldMontant() {
		return jTextFieldMontant;
	}

	public void setjTextFieldMontant(JTextField jTextFieldMontant) {
		this.jTextFieldMontant = jTextFieldMontant;
	}

	public ArrayList<IDescription> getListDescriptionPluging() {
		return listDescriptionPluging;
	}

	public void setListDescriptionPluging(ArrayList<IDescription> listDescriptionPluging) {
		this.listDescriptionPluging = listDescriptionPluging;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonValider;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelClient;
	private javax.swing.JLabel jLabelCompte;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTable jTableClient;
	private javax.swing.JTable jTableCompte;
	private javax.swing.JTextField jTextFieldMontant;
	// End of variables declaration//GEN-END:variables
}
